### PR TITLE
LL-2149: ManagerV2 navigation guard

### PR DESCRIPTION
**Pull request by LFBarreto**
**ManagerV2:**
- Added  NavigationGuard component that works as react-router Prompt but with our own Confirm Modal instead
- blocked navigation while install or updates occur and on allow manager

localhost_8080_webpack_index html

### Type

Feature

### Context

Issue LL-2149

### Parts of the app affected / Test plan

Manager V2 navigation while updates are occurring and on allow manager.

### CODE REVIEW

**Review by gre — COMMENTED** [review]
I think there is something a bit hacky in all of these and I'm not super fan of making buttons handlers conditional based on some external condition they have no connection with. I can see how complex this is going to be when we maintain this over time (like let's say we add more menus, more features,..) but at same time I recognize there is no easy solution for this and it's probably simply a complex problem.

showModal part is also really complex to understand.

I would like to discuss this with more devs in the team if someone have an idea and at least for everyone to ack & get familiar the present solution suggested.

**Comment by LFBarreto** [comment]
> I think there is something a bit hacky in all of these and I'm not super fan of making buttons handlers conditional based on some external condition they have no connection with. I can see how complex this is going to be when we maintain this over time (like let's say we add more menus, more features,..) but at same time I recognize there is no easy solution for this and it's probably simply a complex problem.
> 
> showModal part is also really complex to understand.
> 
> I would like to discuss this with more devs in the team if someone have an idea and at least for everyone to ack & get familiar the present solution suggested.

@gre I agree with you this isn't maintainable as is. I had issues with the mix between modals and navigation that is provided in the sidebar and the already existing hack that redirects to the accounts page if you're on manager trying to access the send and receive modals.
I don't see any easy solution here for now, this needs a rework on the way modals work for me.

**Review by valpinkman — APPROVED** [review]

**Review by gre — APPROVED** [review]
code is much better and i like that the complexity is contained inside NavigationGuard

**Review by MortalKastor — APPROVED** [review]

**Comment by gre** [comment]
we'll test it with the rest

**Pull request merged**
