### PR TITLE
Starred from accounts

### PR DESCRIPTION
**Pull request by juan-cortes**
Completely drop the starred account ids from the settings and use the new field from the accounts model. ~This pr might experience some sorting anomalies since we've adapted the comparator for this new field on https://github.com/LedgerHQ/ledger-live-common/pull/519 but~ (live-common has since been bumped so this is no longer relevant), things that should be tested are: 

- ~On a first launch starred accounts will be lost, this is to be expected since we change the place we are storing them and making a migration makes little sense. Sorry for the inconvenience.~ We've implemented a simple migration logic that will take any existing `starredAccountIds` currently in the settings state and move them to the appropriate account. So please test using an `app.json` that does have starred accounts, it should still have starred accounts when moving to this PR. This can be manually faked by adding a `starredAccountIds` entry into the settings in app.json with an array of account ids. **This field should be eliminated after first launch.**
- We should be able to star accounts
- We should be able to unstar accounts
- We should **no longer** be able to drag and drop items on the sidebar

### Type

Code Quality Improvement, Feature

### CODE REVIEW

**Comment by juan-cortes** [comment]
The current version shouldn't have the ordering issue mentioned above and should pass ci @gre

**Comment by MortalKastor** [comment]
As far as code cleanliness and performance go, I'm really happy to see `react-beautiful-dnd` and the starred accounts array go, but in terms of UX, it might be a bit big for users to swallow losing the star status of their accounts and the ability to order them.

Having a software lose some of the data I put in (which accounts are starred) or some feature I relied on (ordering) takes a pretty big toll on the confidence I have in it, in my book.

**Comment by gre** [comment]
@MortalKastor we'll document this in our release notes but it's important for privacy at least. we could write a migration logic but we should also assess if it's worth it. I think if we release such a major, we could allow ourself to do such changes.
you would fall back on the "star placeholder" and not an empty "wtf are the accounts gone"


to be assess how easy it is to handle a migration logic. i bet it's a pita in context of an encrypted wallet as you would need to "wait" the unlock.

**my reco: let's try to get a migration system in place (that we would not guarantee to keep forever). but if it's too hard to do, we would go for it, i had initially approval from product team to was ok to have a drop of this**

**Comment by juan-cortes** [comment]
I've implemented a simple migration logic, should be tested as described above. I think we've all come to an agreement that this loss for the user might be more important than what we could think and it's not that hard to save our future selves from that headache. 

https://github.com/LedgerHQ/lld-v2/pull/230/files#diff-7e45b8033bf1d9bd2ac59248c6b40330R88-R94

**Review by gre — APPROVED** [review]

**Review by MortalKastor — APPROVED** [review]
👏

**Comment by MortalKastor** [comment]
Maybe we can move QA validation of the migration part for _after_ the merge, so we can test in real condition through an auto-update. WDYT @juan-cortes @gre @Arnaud97234 @nabil-brn ?

**Comment by nabil-brn** [comment]
#### Bug 🔍
After migration, subaccounts are not kept in starred accounts section, it is not supported actually, impossible to star a subaccount.

##### Before
Capture d’écran 2020-02-20 à 12 03 57

##### After
Capture d’écran 2020-02-20 à 12 06 26

#### UI
Starred accounts are clickable but they doesn't appear to be for a simple user.
We probably should add an highlight (colors), lighten the background-color/font color  and change cursor pointer to improve UX.

**Pull request merged**
