### PR TITLE
progress streaming on send flow

### PR DESCRIPTION
**Pull request by gre**
signing

- The point of the feature is to no longer directly show the "please confirm on your device" UI but **only showing it when tx is actually appearing on the device**, which sometimes can take 10s.
- Similarly, after signing with the device, more exchange with the device is happening but it's pointless to continue showing "please confirm on your device" phase, so we enter again a loading phase (with another 10s potential and some progress event)

### CODE REVIEW

**Comment by dasilvarosa** [comment]
I'd prefer a percentage.
Also I'd prefer not to have different wording for signing/broadcasting. If we can have a single one for "Sending transaction" that would be simpler and preferable.

**Review by dasilvarosa — COMMENTED** [review]
1. I'd prefer a percentage or progress bar instead of: Signing (1 of 3).
 
2. Also, I'd prefer not to have different wording for signing & broadcasting. If we can have a single one that would be preferred:

**Sending transaction (xx%)**

**Review by dasilvarosa — CHANGES_REQUESTED** [review]
1. I'd prefer a percentage or progress bar instead of: Signing (1 of 3).
 
2. Also, I'd prefer not to have different wording for signing & broadcasting. If we can have a single one that would be preferred:

**Sending transaction (xx%)**

**Comment by gre** [comment]
this is continuing in #127

**Pull request closed without merging**
